export const FORMATIONS=['Galaxy','Sphere','Heart','DNA','Saturn','Wave','Infinity','Tornado','Butterfly','Black Hole','Cube','Fireworks','Nebula','Quantum Lotus','Torus','Mobius','Rose','Phoenix','Constellation','AURA'];
let cachedText:Array<[number,number]>;
function auraPoints(){if(cachedText)return cachedText;const c=document.createElement('canvas');c.width=360;c.height=120;const g=c.getContext('2d')!;g.fillStyle='white';g.font='900 84px Georgia';g.textAlign='center';g.textBaseline='middle';g.fillText('AURA',180,62);const d=g.getImageData(0,0,c.width,c.height).data;cachedText=[];for(let y=0;y<c.height;y+=2)for(let x=0;x<c.width;x+=2)if(d[(y*c.width+x)*4+3]>100)cachedText.push([x,y]);return cachedText}
export function formation(name:string,n:number,out:Float32Array){for(let i=0;i<n;i++){const a=i/n*Math.PI*2, r=Math.random(), j=i*3;let x=0,y=0,z=0;
 if(name==='Galaxy'){const arm=(i%5)*1.25,t=r*14+arm;x=Math.cos(t)*r*5;y=(Math.random()-.5)*.6*(1-r);z=Math.sin(t)*r*5}
 else if(name==='Sphere'){const p=Math.acos(1-2*r),t=Math.PI*(1+Math.sqrt(5))*i;x=3*Math.sin(p)*Math.cos(t);y=3*Math.cos(p);z=3*Math.sin(p)*Math.sin(t)}
 else if(name==='Heart'){const t=a;x=.19*16*Math.sin(t)**3;y=.19*(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t));z=(Math.random()-.5)*.8}
 else if(name==='DNA'){const t=i/n*22-11,xo=i%2?1:-1;x=Math.cos(t)*1.6*xo;y=t*.32;z=Math.sin(t)*1.6*xo}
 else if(name==='Saturn'){if(i<n*.65){const p=Math.acos(1-2*r);x=2*Math.sin(p)*Math.cos(a);y=2*Math.cos(p);z=2*Math.sin(p)*Math.sin(a)}else{x=Math.cos(a)*(3+r*2);z=Math.sin(a)*(3+r*2);y=(Math.random()-.5)*.18}}
 else if(name==='Wave'){x=(r-.5)*9;z=(Math.random()-.5)*6;y=Math.sin(x*1.5+z)*.8}
 else if(name==='Infinity'){const t=a,d=1+Math.sin(t)**2;x=4*Math.cos(t)/d;y=3*Math.sin(t)*Math.cos(t)/d;z=(Math.random()-.5)*.5}
 else if(name==='Tornado'){const t=r*18;x=Math.cos(t)*(4-r*3);y=r*7-3.5;z=Math.sin(t)*(4-r*3)} else if(name==='Butterfly'){const t=a,b=Math.exp(Math.cos(t))-2*Math.cos(4*t)-Math.sin(t/12)**5;x=Math.sin(t)*b*1.15;y=Math.cos(t)*b*1.15;z=(Math.random()-.5)*.45} else if(name==='Black Hole'){const t=r*24;x=Math.cos(t)*(.35+r*5);z=Math.sin(t)*(.35+r*5);y=(Math.random()-.5)*.22/(r+.08)} else if(name==='Cube'){const e=i%12,u=((Math.floor(i/12)/Math.ceil(n/12))*2-1)*3,s=3,q=()=>((Math.random()-.5)*.045);if(e<4){x=u;y=(e&1)?s:-s;z=(e&2)?s:-s}else if(e<8){x=(e&1)?s:-s;y=u;z=(e&2)?s:-s}else{x=(e&1)?s:-s;y=(e&2)?s:-s;z=u}x+=q();y+=q();z+=q()} else if(name==='Fireworks'){const k=i%12,phi=k/12*Math.PI*2,p=Math.pow(r,.45)*4;x=Math.cos(phi)*p;y=Math.sin(phi)*p;z=(Math.random()-.5)*p*.7} else if(name==='Nebula'){const t=a*3,rr=Math.pow(r,.55)*5;x=Math.cos(t)*rr+(Math.random()-.5);y=(Math.random()-.5)*2;z=Math.sin(t)*rr+(Math.random()-.5)} else if(name==='Torus'){const u=a,v=((i*137.508)%360)*Math.PI/180,R=2.5,q=.85;x=(R+q*Math.cos(v))*Math.cos(u);y=q*Math.sin(v);z=(R+q*Math.cos(v))*Math.sin(u)} else if(name==='Mobius'){const u=a,w=(r-.5)*1.35;x=(3+w*Math.cos(u/2))*Math.cos(u);y=w*Math.sin(u/2);z=(3+w*Math.cos(u/2))*Math.sin(u)} else if(name==='Rose'){const t=a*3,rr=3.8*Math.cos(5*t);x=rr*Math.cos(t);y=rr*Math.sin(t);z=(Math.random()-.5)*.35} else if(name==='Phoenix'){const t=a,wing=Math.sin(t)*4.2;x=Math.sign(Math.cos(t))*Math.abs(wing);y=1.5-Math.abs(x)*.45+Math.sin(t*3)*.5;z=(Math.random()-.5)*.45;if(i%5===0){x=(Math.random()-.5)*.7;y=r*5-3.2;z=(Math.random()-.5)*.5}} else if(name==='Constellation'){const nodes=[[0,3],[-3,1.5],[-1.5,0],[1.2,.7],[3,2],[-2.5,-2],[0,-1.5],[2.8,-2.4]],e=i%8,u=r,A=nodes[e],B=nodes[(e+1)%8];x=A[0]+(B[0]-A[0])*u;y=A[1]+(B[1]-A[1])*u;z=(Math.random()-.5)*.28} else if(name==='AURA'){const pts=auraPoints(),p=pts[i%pts.length];x=(p[0]-180)/38;y=(60-p[1])/38;z=(Math.random()-.5)*.3} else {const t=a,petal=.55+r*(1.15+2.25*Math.pow(Math.abs(Math.sin(4*t)),1.7));x=Math.cos(t)*petal;y=Math.sin(t)*petal*.76;z=Math.sin(r*Math.PI)*.9*(1-r)+(Math.random()-.5)*.15;if(i%9===0){const c=r*1.05;x=Math.cos(t)*c;y=Math.sin(t)*c;z=.65-r*.35}} out[j]=x;out[j+1]=y;out[j+2]=z}}
