import * as THREE from 'three';import type {HandData} from '../types';import {formation} from './formations';
export class ParticleSystem{
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(55,1,.1,100);renderer:THREE.WebGLRenderer; points:THREE.Points; pos:Float32Array;vel:Float32Array;target:Float32Array; count:number; explosion=0; hue=0; last=performance.now();
 constructor(canvas:HTMLCanvasElement,count=3000){this.count=count;this.renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.camera.position.z=11;this.pos=new Float32Array(count*3);this.vel=new Float32Array(count*3);this.target=new Float32Array(count*3);formation('Galaxy',count,this.target);this.pos.set(this.target);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(this.pos,3));const tex=new THREE.CanvasTexture(this.dot());const m=new THREE.PointsMaterial({size:.09,map:tex,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false,color:'#75a7ff'});this.points=new THREE.Points(g,m);this.scene.add(this.points);this.scene.fog=new THREE.FogExp2(0x03040a,.065);this.resize()}
 dot(){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d')!,g=x.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'white');g.addColorStop(.2,'white');g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,64,64);return c}
 setFormation(n:string){formation(n,this.count,this.target)} resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix()}
 burst(){this.explosion=1}
 update(hand:HandData,speed=1,force=1,size=1){const dt=Math.min(.032,(performance.now()-this.last)/1000)*60*speed;this.last=performance.now();const p=this.pos,v=this.vel,t=this.target;const hx=hand.x*5,hy=hand.y*3.2;let color='#75a7ff';if(hand.gesture==='open')color='#ffae42';if(hand.gesture==='fist')color='#ff477e';if(hand.gesture==='pinch')color='#4fffd2';if(hand.gesture==='point')color='#e9fbff';if(!hand.tracked)color='#697080';(this.points.material as THREE.PointsMaterial).color.lerp(new THREE.Color(color),.08);(this.points.material as THREE.PointsMaterial).size=.09*size*(1+Math.max(0,hand.depth)*.5);
 for(let i=0;i<this.count;i++){const j=i*3;let ax=(t[j]-p[j])*.012,ay=(t[j+1]-p[j+1])*.012,az=(t[j+2]-p[j+2])*.012;if(hand.tracked){const dx=p[j]-hx,dy=p[j+1]-hy,dz=p[j+2],d2=dx*dx+dy*dy+dz*dz+.15,d=Math.sqrt(d2);let f=0;if(hand.gesture==='open')f=.16/d2;else if(hand.gesture==='fist'||hand.gesture==='pinch')f=-.105/d2;else if(hand.gesture==='point'&&d<2)f=.05/d2;if(d<5){ax+=dx/d*f*force;ay+=dy/d*f*force;az+=dz/d*f*force}}if(this.explosion>.01){const d=Math.hypot(p[j],p[j+1],p[j+2])+.1;ax+=p[j]/d*this.explosion*.22;ay+=p[j+1]/d*this.explosion*.22;az+=p[j+2]/d*this.explosion*.22}v[j]=(v[j]+ax*dt)*.91;v[j+1]=(v[j+1]+ay*dt)*.91;v[j+2]=(v[j+2]+az*dt)*.91;p[j]+=v[j]*dt;p[j+1]+=v[j+1]*dt;p[j+2]+=v[j+2]*dt}this.explosion*=.92;this.points.rotation.y+=(hand.tracked?hand.x*.003:.0007)*dt;this.points.rotation.z+=(hand.tracked?hand.rotation*.001:0)*dt;this.points.position.y+=(hand.tracked?hand.y*.8-this.points.position.y:-this.points.position.y)*.04;this.points.scale.lerp(new THREE.Vector3(1,1,1).multiplyScalar(1+hand.depth*.35),.05);(this.points.geometry.attributes.position as THREE.BufferAttribute).needsUpdate=true;this.renderer.render(this.scene,this.camera)}
 dispose(){this.renderer.dispose();this.points.geometry.dispose();(this.points.material as THREE.Material).dispose()}}
